In [1]:
import numpy as np
import pandas as pd

# SCALAR (0D) TENSORS

In [2]:
scalar = np.array(12)                                                                                                                                                                                                                                      

In [3]:
scalar

array(12)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

()

# VECTOR ( 1D ) TENSORS

In [6]:
vector = np.array([12, 3, 6, 14])

In [8]:
vector

array([12,  3,  6, 14])

In [9]:
vector.ndim

1

In [10]:
vector.shape

(4,)

## It is a four dimenional vector but a 1 D Tensor as ndim is 1 which is equal to rank of the tensor

# MATRICES (2D) TESNORS

In [11]:
matrices = np.array([[5, 78, 2, 34, 0],
                     [6, 79, 1, 8, 76],
                     [7, 70, 8, 80, 9]])

In [12]:
matrices

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  1,  8, 76],
       [ 7, 70,  8, 80,  9]])

In [13]:
matrices.ndim

2

In [14]:
matrices.shape

(3, 5)

# 3D TENSORS AND HIGHER DIMESNIONS TESNORS

In [13]:
x = np.array([[[5, 78, 2, 34, 0],
              [6, 79, 1, 8, 76],
              [7, 70, 8, 80, 9]],
              [[5, 78, 2, 34, 0],
              [6, 79, 1, 8, 76],
              [7, 70, 8, 80, 9]],
              [[5, 78, 2, 34, 0],
              [6, 79, 1, 8, 76],
              [7, 70, 8, 80, 9]]])

In [14]:
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  1,  8, 76],
        [ 7, 70,  8, 80,  9]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  1,  8, 76],
        [ 7, 70,  8, 80,  9]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  1,  8, 76],
        [ 7, 70,  8, 80,  9]]])

In [16]:
x.ndim

3

## Vectorization of basic tensor operations

## Element wise additions

In [8]:
a = np.array([[5, 78, 2, 34, 0],
                     [6, 79, 1, 8, 76],
                     [7, 70, 8, 80, 9]])

b = np.array([[5, 78, 2, 34, 0],
                     [6, 79, 1, 8, 76],
                     [7, 70, 8, 80, 9]])

_sum = a+b

In [9]:
_sum

array([[ 10, 156,   4,  68,   0],
       [ 12, 158,   2,  16, 152],
       [ 14, 140,  16, 160,  18]])

## Element wise Relu 

In [10]:
a = np.array([[-5, 0, 2, 34, 0],
                     [6, 79, 1, 8, 76],
                     [7, 70, 8, 80, 9]])
_relu = np.maximum(a, 0.)

In [11]:
_relu

array([[ 0.,  0.,  2., 34.,  0.],
       [ 6., 79.,  1.,  8., 76.],
       [ 7., 70.,  8., 80.,  9.]])

## Dot product

In [14]:
np.dot(a,[1,2,3,4,5])

array([137, 579, 536])